# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d732e155a822678a5c3342b26e0684906bf745a12edd2535c88c663de6082cfef71938e1a5897659d7135a6f4ab311d032ad0684de30da519de9ac84961da1b4

test:
  secret_key_base: b2a83c262fbe5ff1c3cd3ea7f4b792de758047945c7a68a1bfbb65dadbaab2facd1b6255f50b16e1d1c584f25a2588194353e910548c2d33a0f166bb8d93e8d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
